### ISSUE TITLE
Update study schema - Target genes

### ISSUE THREAD

**Issue by ESapenaVentura** [morphic-bio/metadata-schema#20]
Following discussion in internal meeting, discuss and decide on how to best collect metadata for target genes

Current approach may be unsuitable for users 

- Filling out 1000s of genes manually is not feasible - Barrier of entry
- Free text field is not a great solution - We end up with too much variation for the same genes/set of
- Maybe attached document - Need to coordinate validation of document and how to do it

**Comment by gabsie** [comment]
This was implemented with the new schema for gene alteration, and cell lines attributes
