### ISSUE TITLE
fix zenhub board for Morphic

### ISSUE THREAD

**Issue by amnonkhen** [morphic-bio/metadata-schema#3]
- [x] connect github organisation to zenhub. Admin on org is needed, @ESapenaVentura to ask one of the PIs. 
- [x] Convert to epics the proper tickets
- [x] create a github team (maybe 2) for devs and wranglers, assign permissions to repos
- [x] Add labels to the tickets
- [x] Assign people to their tickets
- [x] convert zenhub issues to github issues
- [x] disable new zenhub issue creation - Is this possible?
- [ ] setup zenhub releases, assign issues

**Comment by ESapenaVentura** [comment]
A GitHub team has been created - DRACC-EBI, containing the following team members:

@dipayan1985 @theisuru @amnonkhen @gabsie @anu-shiva @ESapenaVentura @KociOrges 

I don't think I am missing anyone?

I have given that team access to write permissions - I think for the people we want higher permissions we should create another team or assign per person!

**Comment by ESapenaVentura** [comment]
The only 2 tickets I couldn't asssign are #4 and #6 - Isuru needs to accept the invitation to the DRACC-EBI team

**Comment by ESapenaVentura** [comment]
This ticket needs @gabsie to accept the invitation - I think the comment can't be copied until then

**Comment by ESapenaVentura** [comment]
Actually, I just realised - Zenhub issues that are copied loose the comments. It doesn't really tell you before doing this action (Kinda annoying), so I think it's better we leave these tickets as is and just don't create new ones

**Comment by ESapenaVentura** [comment]
I don't think there's a way to disable zenhub issues - There is not a lot of documentation about it... But I have also checked the options in the workspaces, account etc and it doesn't seem to be an option

**Comment by anu-shiva** [comment]
Zenhub has access to morphic repos
