### ISSUE TITLE
dbGaP templates and submission process

### ISSUE THREAD

**Issue by anu-shiva** [morphic-bio/metadata-schema#31]
- to looking at the dbGaP templates and submission process
- do a test submission

**Comment by gabsie** [comment]
question: we are talking about the raw sequencing files there.

**Comment by gabsie** [comment]
dbGap is slow, we have some connections to EGA, but also they're mentioning Anvil a lot (NIH), so this for the moment is being closed.
Also not possible to do this as a test.
