### ISSUE TITLE
Adapt metadata-schema-publisher for MorPhiC to solve 'allOf' property

### ISSUE THREAD

**Issue by KociOrges** [morphic-bio/metadata-schema#32]
MorPhiC type metadata-schemas include a system-related property named 'allOf', which needs to be dereferenced to include the properties described in the system/document.json schema. Add functionality to the adapted version of the metadata-schema-publisher for MorPhiC to account for this.

**Comment by KociOrges** [comment]
Implemented in this branch: https://github.com/ebi-ait/metadata-schema-publisher/tree/feature/mc-4_morphic_publisher

**Comment by gabsie** [comment]
@ESapenaVentura  to check with Tony about removing  Allof and moving properties to root
