### ISSUE TITLE
Metadata schema improvement - Biomaterials, Cell lines etc

### ISSUE THREAD

**Issue by ESapenaVentura** [morphic-bio/metadata-schema#39]
Based on our conversation with one of the DPCs, and an internal conversation later, we have decided that we are going to re-evaluate the cell line schemas to more accurately collect information about non-differentiated cell lines that can be used as samples in, e.g., benchmarking datasets.

 

## Acceptance Criteria
- [ ] Evaluate the spreadsheets and try to adapt to the data model described above
- [ ] Present the results to @anu-shiva 
- [ ] Present the results to the DPCs/DRACC
- [ ] Apply the reviewed changes to the JSON schema

[Cell Line spreadsheet](https://docs.google.com/spreadsheets/d/1hAE2ilbAdk9Nm3qy-doWqwSA1oi2v8faqH7oSdC8XrU/edit#gid=1187886394)

**Comment by gabsie** [comment]
I think this task is superceded by the new clonal cell line proposal, so closing
