### ISSUE TITLE
Update gene_alteration_protocol

### ISSUE THREAD

**Issue by ESapenaVentura** [morphic-bio/metadata-schema#55]
In green, the fields that need to go into an array of subschemas:

[Gene_alteration_pooled.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHR1Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--007f0e40f4d589a234d610cd082141bf3e238027/Gene_alteration_pooled.xlsx)

**Comment by ESapenaVentura** [comment]
https://github.com/morphic-bio/metadata-schema/pull/58

**Comment by anu-shiva** [comment]
Reviewed the PR. The fields are go into an array of subschemas are correct. 
Next steps: to generate a spreadsheet including this extra sheet reflecting the array of subschemas?
