### ISSUE TITLE
use cases for schema to spreadsheet generator

### ISSUE THREAD

**Issue by gabsie** [morphic-bio/metadata-schema#65]
Anu to provide use cases for generation of DPC experiment-specific spreadsheet generation

**Comment by gabsie** [comment]
from Alex: Thank you for the use-case spreadsheets, Anu! They are very helpful. To assist you and Enrique potentially, with aligning the naming between the schemas and the existing templates, I compared the use-case templates with the one created by the client. I've identified several fields missing across tabs. Some of these fields are linked between tabs however, and should be generated dynamically during the process rather than explicitly included in the schemas:

1. Clonal Cell Line:

PARENTAL CELL LINE NAME
CLONE ID
GENE EXPRESSION ALTERATION ID
CELL LINE GENERATION PROTOCOL
TREATMENT/CONDITION
WT/CONTROL STATUS
2. Expression Alteration:

GENE EXPRESSION ALTERATION ID
ALTERED GENE SYMBOLS
ALTERED GENE IDs
3. Differentiated Product:

DIFFERENTIATED CELL LINE ID
Input CELL LINE ID
DIFFERENTIATION PROTOCOL ID
TREATMENT/CONDITION
WT/CONTROL STATUS
4. Undifferentiated Product:

CELL LINE DESCRIPTION
Input CELL LINE ID
TREATMENT/CONDITION
WT/CONTROL STATUS
5. Library Preparation:

LIBRARY PREPARATION ID
LIBRARY PREPARATION PROTOCOL ID
DISSOCIATION PROTOCOL ID
Input DIFFERENTIATED CELL LINE ID
6. Sequence File:

CONTENT DESCRIPTION
Input LIBRARY PREPARATION ID
SEQUENCING PROTOCOL ID

**Comment by gabsie** [comment]
[Use cases folder](https://drive.google.com/drive/folders/1WyMh_4Ze2fH-9i00tK2Zz1t2HMJc1Vrh)
this folder contains a [Use-case:moprhic spreadsheets](https://docs.google.com/document/d/1BPkivaObdVxT-Ps4X0sydKAL39_bVM5ifdqfbkNC1J4/edit) that links to individual spreadsheets

**Comment by KociOrges** [comment]
A full and use-case specific v7 spreadsheets for MorPhiC have been uploaded to the [use-cases folder](https://drive.google.com/drive/folders/1WyMh_4Ze2fH-9i00tK2Zz1t2HMJc1Vrh). This update also addresses a minor duplication issue noticed in the Expression Alteration tab.
